ALTER TABLE Tyres ADD COLUMN LocalCategory	int DEFAULT NULL;
ALTER TABLE Tyres ADD COLUMN BarCode 	varchar(30) DEFAULT NULL ;
ALTER TABLE Tyres ADD COLUMN ManCode varchar(2) DEFAULT NULL;

ALTER TABLE Tyres ADD COLUMN TyreType varchar(1) DEFAULT NULL;
ALTER TABLE Tyres ADD COLUMN OEList varchar(30) DEFAULT NULL;
ALTER TABLE Tyres ADD COLUMN Ply varchar(4) DEFAULT NULL;
ALTER TABLE Tyres ADD COLUMN Construction varchar(2) DEFAULT NULL;
ALTER TABLE Tyres ADD COLUMN Season varchar(2) DEFAULT NULL;
    