ALTER TABLE Tyres ADD COLUMN ManufacturerName 	varchar(50) NOT NULL DEFAULT '';
ALTER TABLE Tyres ADD COLUMN ExcludePL		varchar(10) NOT NULL DEFAULT '';
ALTER TABLE Tyres ADD COLUMN RunFlat		varchar(10) NOT NULL DEFAULT '';
ALTER TABLE Tyres ADD COLUMN ExtraLoad		varchar(10) NOT NULL DEFAULT '';
ALTER TABLE Tyres ADD COLUMN LocalGroup		varchar(10) NOT NULL DEFAULT '';
